Segunda parte
angular-bolivia/todo-list-tutorial pull request #4
Opened 2019-10-23 22:11 UTC by DentVega

- Añadido del boton para eliminar una tarea
- Añadido del boton para editar una tarea

2019-10-23 22:17 UTC, combimauri requested changes

2019-10-23 22:17 UTC, mauricioarce commented on src/app/app.component.html
> +         <a class="btn  btn-red" (click)="eliminarTarea(i)">
```suggestion
         <a class="btn btn-red" (click)="eliminarTarea(i)">
```

2019-10-23 22:17 UTC, mauricioarce commented on src/app/app.component.html
> +      <li *ngFor="let tarea of listaTareas; index as i">
En vez de **i**, tal vez podrías usar algo como **indice**
```
      <li *ngFor="let tarea of listaTareas; index as indice">
```

2019-10-23 22:17 UTC, mauricioarce commented on src/app/app.component.ts
> +  editar(index) {
Está cool :) Podrías ponerle a este método el nombre de **marcarTareaComoCompletada** cuando lo actualices de acuerdo a lo que hablamos

2019-10-24 02:01 UTC, combimauri requested changes

2019-10-24 02:01 UTC, combimauri commented on src/app/app.component.html
> +         <button class="btn btn-red" (click)="marcarTareaComoCompletada(indice)">
Aquí podrías pasar directo la tarea en vez de mandar solo el índice

2019-10-24 02:01 UTC, combimauri commented on src/app/app.component.html
> +         <a class="btn btn-red" (click)="eliminarTarea(indice)">
Creo que esto estilos no existen

2019-10-24 02:01 UTC, combimauri commented on src/app/app.component.html
> +        <label [ngClass]="tarea.terminado ? 'strike' : 'null'">{{ tarea.detalle }}</label>
porfa, usa algo así:
```
[ngClass]="{ 'tarea-completada': tarea.completada }"
```
Estás asignado una clase null si es que no aplica la condición, esa clase no existe.

2019-10-24 02:01 UTC, combimauri commented on src/app/Tarea.model.ts
> +export class Tarea {
El nombre de este archivo es incorrecto, deberías usar kebab case, debería llamarse: tarea.model.ts

2019-10-24 02:01 UTC, combimauri commented on src/app/Tarea.model.ts
> +  terminado: boolean;
Este atributo debería ser: terminada o completada, en femenino

2019-10-24 02:01 UTC, combimauri commented on src/app/app.component.css
> +.strike {
Mejor si usas un nombre como: task-completed o su equivalente en español

2019-10-24 02:01 UTC, mauricioarce commented on src/app/app.component.ts
> +
Elimina esta línea blanca

2019-10-24 03:08 UTC, combimauri requested changes

2019-10-24 03:08 UTC, mauricioarce commented on src/app/app.component.ts
> +  marcarTareaComoCompletada(tarea, indice) {
No es necesario que mandes el indice en este método

2019-10-24 03:08 UTC, mauricioarce commented on src/app/app.component.ts
> +    this.listaTareas[indice] = tarea;
Esta línea de código es innecesaria

2019-10-24 03:08 UTC, mauricioarce commented on src/app/app.component.html
> +            <button class="btn btn-red" (click)="eliminarTarea(tarea)">
```suggestion
            <button class="btn btn-red" (click)="eliminarTarea(indice)">
```

2019-10-24 03:27 UTC, DentVega commented
@mauricioarce corregido

2019-10-24 03:33 UTC, combimauri reviewed
Buenísimo. Agrega las instrucciones al Readme y listo :)

2019-10-24 07:15 UTC, DentVega commented
@mauricioarce  instrucciones de la segunda parte añadidas

2019-10-24 14:43 UTC, combimauri approved these changes

2019-10-24 14:43 UTC, merged